### ISSUE TITLE
Will Not Configure on Fedora 28

### ISSUE THREAD

**Issue by tvollscw** [ztefn/haguichi#16]
Installed Haguichi using the instructions [for Fedora here](https://www.haguichi.net/download/).
Successfully installed Hamachi through their rpm.
But after getting Haguichi up and running, it won't go past the 'Hamachi is not configured' screen.
I select the Configure option, I enter in my password, it freezes there for a few seconds, then unfreezes, but doesn't update anything.

When trying to sudo haguichi within the terminal, I do get an here that reads:

> 
> No protocol specified
> Unable to init server: Could not connect: Connection refused
> 
> (haguichi:7059): Gtk-WARNING **: 17:17:55.533: cannot open display: :0
> 

I feel like this might have to do with me running on Wayland, but I wasn't entirely sure..

**Comment by ztefn** [comment]
Hi @tvollscw,

Did you also install `redhat-lsb-core` _before_ installing the Hamachi rpm as instructed? Because that should have helped to make configuring a bit smoother on Fedora.

Anyway, if you start Haguichi from terminal using the following command **without sudo**, you can better see what Haguichi detects and sees when trying to configure and restart hamachi:
`haguichi --debug`

Please copy and paste this output if you want me to take a look at it.

**Comment by tvollscw** [comment]
Hey @ztefn,
Yes, I verified before installing that `redhat-lsb-core` was already installed.
Fortunately, when running `haguichi --debug`, everything seems to work now.. I'll restart my computer and see if the issue persists. Very strange.

**Comment by tvollscw** [comment]
Unfortunately, I was not able to repeat the error. On both of my Fedora 28 machines (where the issue originally happened), the issue had seemingly fixed itself over time. Will post back here if it occurs again to me in the future with any other machines..

**Comment by ztefn** [comment]
Once you shutdown, the hamachi service will undoubtedly have been stopped. And then when you boot your computer and start the hamachi service, the updated configuration is finally used. Effectively a reboot to restart a service, like they do on Windows... ;)

**Comment by tvollscw** [comment]
Terrific! Makes sense. Glad you were able to find the issue and that I wasn't crazy. Right on!

**Comment by martindale** [comment]
I'm experiencing this issue on Ubuntu, perpetual hang on clicking "configure".

**Comment by ztefn** [comment]
@martindale Please quit Haguichi completely and start it in debug mode from a terminal using the following command:
`haguichi --debug`

Click configure one or two times. Copy the output from the terminal and paste it here or send it to me privately.

Only with the debug output I can try to figure out the source of your issue.
