### ISSUE TITLE
Whenever I try to connect this is the error i get

### ISSUE THREAD

**Issue by Azodion** [ztefn/haguichi#23]
Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address

I've looked up some fixes for this, but there seems to not be any. please help. Im just trying to play with some friends

**Comment by ztefn** [comment]
Hi Azodion,

There appears to be a problem with opening an authentication dialog on your system. There could be multiple causes for this, so let me ask some questions:
- What Linux distribution and version are you running?
- Are you running this distribution inside some VM or container like Crouton?
- Are you using X or Wayland as display server?
- Can you successfully run other applications that require super user authentication or do they fail in the same way?

**Comment by ztefn** [comment]
@Azodion I can't help if you're not replying my questions.
