### ISSUE TITLE
RDP resolution setting

### ISSUE THREAD

**Issue by detekutod** [ztefn/haguichi#24]
Hello, could you please advise if it's possible to change the resolution of RDP client? 
I connect to various machines on W7 and W10, the connection is awesome, everything works great - but it seems like Haguichi doesn't get client's screen resolution, it is always 800 x 600.

Thanks

**Comment by ztefn** [comment]
Hi @detekutod,

I get the feeling you don't have any idea about the order of things. So here you go:
1. Haguichi lets you to control your Hamachi client through a nice graphical user interface.
2. Your Hamachi client itself sets up the actual networks and connection between peers.
3. Anything you do over this network (RDP, file sharing, gaming, etc) is handled by specific applications (like an RPD client).

So, the connection being awesome should be attributed to Hamachi and _not_ Haguichi (it merely asks your Hamachi client to connect).

Changing the resolution of your RDP client is domain of your... RDP client. Do you have any idea which RDP application/command you are using?

**Comment by detekutod** [comment]
Dear @ztefn 

Thanks for your reply. Sure I do understand that **Haguichi** just provides a convenient and friendly GUI, and many thanks for this. But one of the things coming to my mind when just one of the good features supported by the GUI seems not to work as it would be more logical, is _maybe it's not supported on the side of the GUI_ or _maybe I didn't find this option in the GUI_

Sure I understand that probably I just didn't spot it, but I've checked the terminal options of Hamachi before decided to ask the question about Haguichi.

Thank you.

**Comment by detekutod** [comment]
Sorry @ztefn 

Stupid me :D I figured out how rdp client works ) Everything is good now )

**Comment by ztefn** [comment]
@detekutod Out of curiosity: which RDP client was (pre)installed on your system and were you making use of? And have you been able to change the resolution for this RDP client?

**Comment by detekutod** [comment]
@ztefn yes, there was preinstalled **rdesktop**, I didn't find manual options for definite resolution, but the full screen mode can be launched with simple -f in command, added it to command in Haguichi, it's all good )
