### ISSUE TITLE
Suru icons need update to the new (more square) Yaru style

### ISSUE THREAD

**Issue by ztefn** [ztefn/haguichi#25]
As discussed in ubuntu/yaru#1564.

@ubuntujaggers Can you provide a rough estimate when you will have time for this? Then I can take this into account for release planning.

**Comment by ztefn** [comment]
@ubuntujaggers are you still interested in picking up this task?

**Comment by ubuntujaggers** [comment]
Really sorry @ztefn, I missed this! Had a busy couple of months but I can do it this week, will be done by Friday 👍

**Comment by ubuntujaggers** [comment]
Done, see PR :+1:
