### ISSUE TITLE
Not showing on Elementary OS app center

### ISSUE THREAD

**Issue by cowi2004** [ztefn/haguichi#29]
The title, Haguichi is not showing at the app center.

**Comment by ztefn** [comment]
Well, it is in there. See: https://appcenter.elementary.io/com.github.ztefn.haguichi/

**Comment by cowi2004** [comment]
Hey.

Yeah, I can access the page, but I think there is a problem. When I try to access via the app center app, it won´t show up

**Comment by cowi2004** [comment]
![Screenshot from 2020-01-25 18-14-53](https://user-images.githubusercontent.com/58893440/73127414-a2fb9200-3f9e-11ea-8e4d-d24442325a0b.png)

**Comment by ztefn** [comment]
Can you see any third party apps in app center at all?

**Comment by cowi2004** [comment]
Well, now that you ask, I think i´m not able to see any third party apps, unless thy´re referred as "non-curated apps" on the store

**Comment by ztefn** [comment]
I think you are experiencing the something similar to this issue: elementary/appcenter#916

The solution there seemed to be running the following command in the terminal:
`sudo appstreamcli refresh --force`

**Comment by cowi2004** [comment]
I´m sorry man, but that doesn´t seem to be the answer. Can I try anything else?

I´m sorry for asking you, but I´m a newbie

**Comment by ztefn** [comment]
What's the output when you run `sudo apt update` in the terminal?

**Comment by cowi2004** [comment]
The output is:

gabriel@HOSTNAMEserver:~$ sudo apt update
sudo: unable to resolve host HOSTNAMEserver: Connection timed out
[sudo] password for gabriel:       
Hit:1 http://uy.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 https://download.docker.com/linux/ubuntu bionic InRelease [64,4 kB]                                                   
Get:3 http://uy.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]                                                                                 
Get:4 http://uy.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]                                                                               
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                         
Hit:6 http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease       
Fetched 228 kB in 1s (221 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
gabriel@HOSTNAMEserver:~$

**Comment by ztefn** [comment]
Apparently, there aren't any elementary OS repositories present or enabled on your system. So technically you are just running on Ubuntu 18.04 LTS.

So to install Haguichi you can follow the [download](https://www.haguichi.net/download/) instructions for Ubuntu:
`sudo add-apt-repository -y ppa:webupd8team/haguichi`
`sudo apt update`
`sudo apt install -y haguichi`

If you really intended to use elementary OS I would suggest a complete re-installation of the OS.

**Comment by cowi2004** [comment]
Hey dude, it worked. Thanks for everything, have a nice day!  :D
