### ISSUE TITLE
Errors Downloading Haguichi (Ubuntu)

### ISSUE THREAD

**Issue by hamacha** [ztefn/haguichi#33]
I am unable to download Haguichi.

When I try to follow the process listed on the Haguichi download page, I get a GPG error after running the "apt update" command telling me that several signatures were invalid, followed by several "KEYEXPIRED #########" lines. 

After checking for expired keys, I found that a key from Haguichi expired in July 2020. However, when I attempt to update the expired can, I can see that no changes are made to that key, and it remains expired.

Are you able to shed any light on this?

Thanks!

**Comment by ztefn** [comment]
Hello @hamacha,

- What Linux distribution are you using?
- What is the exact version of that distribution?
- What is the complete error message? (please copy paste the whole thing)

Thank you

**Comment by hamacha** [comment]
Thank you for your response!

Linux distribution: *ubuntu 14.04 LTS*

Complete error message (beginning from the first 'Err' tag:

Err http://repository.services.logmein.com stable/main amd64 Packages

Err http://repository.services.logmein.com stable/main i386 Packages

Err http://repository.services.logmein.com stable/main amd64 Packages

Err http://repository.services.logmein.com stable/main i386 Packages

Err http://repository.services.logmein.com stable/main amd64 Packages

Err http://repository.services.logmein.com stable/main i386 Packages

Hit http://repository.services.logmein.com stable/main amd64 Packages
Hit http://repository.services.logmein.com stable/main i386 Packages
Ign http://repository.services.logmein.com stable/main Translation-en_US
Ign http://repository.services.logmein.com stable/main Translation-en
Fetched 22.8 kB in 4s (4,633 B/s)
Reading package lists... Done
W: GPG error: http://repository.services.logmein.com stable InRelease: The
following signatures were invalid: KEYEXPIRED 1594984969 KEYEXPIRED
1594984969 KEYEXPIRED 1547465069 KEYEXPIRED 1594984969 KEYEXPIRED
1594984969 KEYEXPIRED 1580832666 KEYEXPIRED 1654845757 KEYEXPIRED
1594984969 KEYEXPIRED 1594984969 KEYEXPIRED 1547465069 KEYEXPIRED
1594984969 KEYEXPIRED 1594984969 KEYEXPIRED 1580832666 KEYEXPIRED
1594984969 KEYEXPIRED 1594984969 KEYEXPIRED 1547465069 KEYEXPIRED
1594984969 KEYEXPIRED 1594984969 KEYEXPIRED 1580832666

**Comment by ztefn** [comment]
Thats very clarifying for sure...!

1. Ubuntu 14.04 LTS [reached end of life on April 19, 2019](https://www.omgubuntu.co.uk/2019/04/ubuntu-14-04-end-of-life).
2. Haguichi is only available for Ubuntu 16.04 and newer.
3. The repository in your error is *not* the Haguichi repository, this is the Haguichi repository: https://launchpad.net/~webupd8team/+archive/ubuntu/haguichi
4. I don't know which Haguichi download page you visited, but this is the official one: https://haguichi.net/download/

**Comment by hamacha** [comment]
All very helpful, thank you so much!

**Comment by hamacha** [comment]
Successfully installed haguichi with your help - thanks! Now getting an
error logging into hamachi.

Now receiving an error as I try to log in. I disabled firewalls, and
checked for an IPv6 error, but that doesn't seem to be part of the issue.
Here's the error I keep receiving:

09.25 11:06:34.585 ses: << msg_helo ..
09.25 11:06:34.591 ses: io error, send, 111
09.25 11:06:34.591 ses: error 3, retryable yes
09.25 11:06:34.597 ses: go_offline, keep_tunnels 0, login_on_relaunch 0,
actual state 1 ..
09.25 11:06:34.603 ipc: 0213f730 del client
09.25 11:07:04.689 ipc: user [redacted] allowed
09.25 11:07:04.689 ipc: 0214f670 add client 172
09.25 11:07:04.690 cfg: save()
09.25 11:07:04.697 cfg: hks: [0] [2048]
09.25 11:07:04.697 cfg: hkc: [0] [2048] [2048]
09.25 11:07:04.697 ipc: 0214f670 del client
09.25 11:07:04.705 ipc: user [redacted] allowed
09.25 11:07:04.705 ipc: 0213f9e0 add client 173
09.25 11:07:04.706 cfg: save()
09.25 11:07:04.712 cfg: hks: [0] [2048]
09.25 11:07:04.712 cfg: hkc: [0] [2048] [2048]
09.25 11:07:04.713 sys: connmgr_go_online, reconnect 0
09.25 11:07:04.725 ses: on_conn_state(connected, 0x0)
09.25 11:07:04.725 ses: select conn mode 'dns lb'
09.25 11:07:04.725 ses: go_offline, keep_tunnels 1, login_on_relaunch 0,
actual state 4 ..
09.25 11:07:04.737 sys: go_online, reconnect 0
09.25 11:07:04.743 ses: resolving hamachi-data-center.logmein-gateway.com ..
09.25 11:07:04.763 ses: resolving hamachi-list.14.logmein-gateway.com ..
09.25 11:07:04.829 ses: selected (173.199.31.55, 6897)
09.25 11:07:04.829 ses: selected 01 connection type
09.25 11:07:04.834 ses: resolving 173.199.31.55 ..
09.25 11:07:04.847 ses: connecting to 173.199.31.55:12975 ..
09.25 11:07:04.854 ses: connection is established
09.25 11:07:04.861 ses: control connection is bound to 10.0.0.97
09.25 11:07:04.861 ses: << msg_helo ..

Hopefully this highlights what the problem may be!

**Comment by ztefn** [comment]
Something is apparently blocking the connection to the hamachi gateway. I don't know either what that something is, unfortunately. I'm sorry...
