### ISSUE TITLE
is:issue is:open why i cant connect to haguichi? everytime i try, he says "System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is off ".

### ISSUE THREAD

**Issue by enzomiassi** [ztefn/haguichi#35]

**Comment by ztefn** [comment]
What Linux distribution (and version) are you using?
What are the steps you take to get this error?
Where do you see this error?
Can you attach a screenshot?

**Comment by ztefn** [comment]
Closing for lack of information and response.

**Comment by enzomiassi** [comment]
heyy Man, thanks for answer me. Im using a debian gnu/Linux, version 10 (buster).
As soon i start The haguichi, He ask for my password, and after i do that, He says "error when connecting"
like you see in the pictures I sent you

**Comment by enzomiassi** [comment]
![Uploading 16081436351246568723569542119516.jpg…]()

**Comment by enzomiassi** [comment]
![Uploading IMG_20201216_153459.jpg…]()

**Comment by ztefn** [comment]
I don't see your screenshots. Seems like something went wrong with your upload...

Debian 10 should be using systemd by default, so its very strange your system is not. Did you change init system?

Anyway, you can manually override the (auto-detected) init system that Haguichi will use. To use sysvinit run the following command in a terminal:
`gsettings set com.github.ztefn.haguichi.commands.init-system service`

Or to use init.d:
`gsettings set com.github.ztefn.haguichi.commands.init-system init.d`

**Comment by enzomiassi** [comment]
cool, thanks man. So, i just write this command in a random terminal, and its done?

**Comment by ztefn** [comment]
Yes. I think the second one (init.d) is most likely to work without systemd on Debian.

You can check the value that is currently set by running:
`gsettings get com.github.ztefn.haguichi.commands init-system`

And you can set the value back to auto-detection by running:
`gsettings set com.github.ztefn.haguichi.commands.init-system auto`

**Comment by enzomiassi** [comment]
when i use both commands, the terminal shows me this
gsettings set com.github.ztefn.haguichi.commands.init-system init.d
Usage:
  gsettings [--schemadir SCHEMADIR] set SCHEMA[:PATH] KEY VALUE

Set the value of KEY to VALUE

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema
  VALUE     The value to set

**Comment by enzomiassi** [comment]
but when i use this command "gsettings get com.github.ztefn.haguichi.commands init-system"
they show me this 
gsettings get com.github.ztefn.haguichi.commands init-system
'auto

**Comment by ztefn** [comment]
I'm sorry, I made a typo. It should be (space after commands instead of period):
`gsettings set com.github.ztefn.haguichi.commands init-system init.d`

**Comment by enzomiassi** [comment]
MANNN YOU ARE THE BESST, IT WORKED, THANKSSS BROOO

**Comment by ztefn** [comment]
Great! I hope the situation that your system is not booted using [systemd](https://wiki.debian.org/systemd) doesn't give you any other problems. You might want to change/fix that eventually.
