### ISSUE TITLE
My PID 1 is not "systemd"

### ISSUE THREAD

**Issue by 27-10-2001** [ztefn/haguichi#36]
Hello, I have a problem, when connecting haguichi writes "System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down "
What should I do?

**Comment by 27-10-2001** [comment]
Thank you, found a solution in past issues

**Comment by ztefn** [comment]
May I ask what Linux distribution (and version) you are using where you encounter this? And if you are running Linux natively or inside some emulation layer like WSL or Crouton?

**Comment by 27-10-2001** [comment]
I am use MX Linux (version: MX-19.3_x64 KDE, “ahs”, 64 bit only) оn a laptop on native linux

**Comment by ztefn** [comment]
Ah, very interesting! It seems that MX Linux supports both sysvinit and systemd and can easily switch between them from the boot menu. I think for the next release I can improve the automatic init system detection to handle this by also checking the process name for PID 1.

**Comment by 27-10-2001** [comment]
Thank you, my compliments!
