### ISSUE TITLE
Haguichi seems to corrupt Hamachi on Ubuntu 20.04

### ISSUE THREAD

**Issue by LeonineKing1199** [ztefn/haguichi#38]
I'm using Haguichi version 1.4.3 and Hamachi version 2.1.0.203

I've noticed on 64-bit Ubuntu 20.04 that if I startup Haguichi, Hamachi will randomly crash and then be stuck in a persistent crash-loop. I know this because starting the Hamachi service requires password input so I'll get random prompts for a password while doing other things.

Let me know if any more information is required!

**Comment by ztefn** [comment]
What makes you think Haguichi somehow "corrupts" Hamachi and it doesn't simply crash on its own merit?

Hamachi version 2.1.0.203 packages have been build years ago for Ubuntu 16.04 LTS. Later Ubuntu releases ship with newer glibc which conflict with the (older) builds of Hamachi. This problem [is known](https://community.logmein.com/t5/LogMeIn-Hamachi-Discussions/Hamachi-randomly-disconnects-on-Ubuntu-20-04/td-p/222430) and LogMeIn promised a new release "[very soon](https://community.logmein.com/t5/LogMeIn-Hamachi-Discussions/Hamachi-randomly-disconnects-on-Ubuntu-20-04/m-p/223828/highlight/true#M18606)" months ago but still haven't devlivered. Also, this problem [happened before](https://askubuntu.com/questions/966463/hamachi-not-working-on-ubuntu-17-10), so they apparently never learned nor cared.

**Comment by LeonineKing1199** [comment]
Heh, good to know.

What's interesting about it is, the crashes only seem to happen once Haguichi is started. If I never start the application, I can seemingly use Hamachi without errors.

What do you think the cause for that would be?

If it was a simple glibc version errors, I'd be expecting Hamachi to crash on its own all the time.

**Comment by ztefn** [comment]
Haguichi will call the Hamachi command line every 15 seconds (or whatever you set the network update interval in preferences) to update the client status (`hamachi status` and `hamachi list`). Doesn't make any sense this would trigger Hamachi to crash, but who knows what's going on. You could check the Hamachi logs in **/var/lib/logmein-hamachi**

Also, you can see everything Haguichi does if you start it from the terminal in debug mode:
`haguichi --debug`

**Comment by LeonineKing1199** [comment]
Alright, so I started up Haguichi again using `--debug`. Here's some of the crash info:
```
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 23.981/23.981/23.981/0.000 ms

[10:28:40.809151 ENVIRONMENT] [Controller.has_internet_connection] Success!
[10:28:40.812623 HAMACHI] [Hamachi.get_info] Hamachi does not seem to be running.
Run '/etc/init.d/logmein-hamachi start' to start daemon.

[10:28:40.812652 ENVIRONMENT] [Utils.path_exists] FileUtils tested true for path /var/lib/logmein-hamachi/h2-engine-override.cfg
[10:28:40.812667 INFO] [Controller.status_check] Not started.
[10:28:40.812807 INFO] [Controller.update_list] Hamachi connection lost.
[10:28:40.829971 INFO] [Controller.restore_connection_cycle] Trying to reconnect...
```

Looking at the Hamachi crash log, I see this:
```
date/time]
01/22/2021 10:28:28.119

[version]
Linux 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64Hamachi linux-2.1.0.203

Process [1537]

[error]
Segmentation fault

[stack]
hamachid() [0x52e3db]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f4cf9459210]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x11e) [0x7f4cf94b037e]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x19) [0x7f4cf970fc29]
hamachid() [0x50a5d0]
hamachid() [0x50929e]
hamachid() [0x487959]
hamachid() [0x4897e8]
hamachid() [0x48a6ec]
hamachid() [0x48db6c]
hamachid() [0x5106fd]
hamachid() [0x50eb90]
hamachid() [0x446c9e]
hamachid() [0x4bebe2]
hamachid() [0x40709e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f4cf943a0b3]
hamachid() [0x4076cf]
```

Seems like it's indeed a libc issue.

I think it's honestly just invoking one of the commands lol. Either `status` or `list` is the culprit, if that's what Haguichi calls.

Alright, I'll go ahead and close this issue as Haguichi is technically doing nothing wrong, it's just a poor implementation on part of the Hamachi devs.

Thank you for your patience!

**Comment by ejtagle** [comment]
I have created a possible workaround for this, at least, until LogmeIn decides to actually fix the underlying bug: https://github.com/ejtagle/hamachi-fix-ubuntu20.04-or-newer

**Comment by LeonineKing1199** [comment]
@ejtagle you are way too incredibly brilliant at software lol.
