### ISSUE TITLE
issues account and constant Dc

### ISSUE THREAD

**Issue by MissLav** [ztefn/haguichi#40]
cant loginto account just stuck (pending)
added the account to try to fix another issue of losing connection like every 5 min

**Comment by MissLav** [comment]
and also i do not know where the config files are stored they arnt in .config or .local/share

**Comment by ztefn** [comment]
**This is not the support page for Hamachi.** This is an issue tracker for Haguichi, which provides a graphical frontend for Hamachi.

You need to approve the attach request to your account on the LogMeIn website. To quote the actual [LogMeIn Support page](https://support.logmeininc.com/central/help/how-to-attach-an-unattached-client-to-a-logmein-account-central-t-hamachi-add-attachexisting):
_The Account Holder or administrator will see the attachment request on the Join Requests page for the specified LogMeIn account. The Account Holder or administrator must approve or deny the request._

Losing connection like every 5 minutes is an issue with Hamachi itself I cannot help you with.

Hamachi configuration files are located in the folder `/var/lib/logmein-hamachi` which you can open in your file manager directly from Haguichi by opening the (hamburger) menu on the top right. The selecting "Configuration" and then "Open Folder".

**Comment by MissLav** [comment]
thank you for the info sorry for bothering you have a great night
