### ISSUE TITLE
Authentication is needed to run systemctl as superuser

### ISSUE THREAD

**Issue by odxscholars** [ztefn/haguichi#41]
Every time I use Haguichi, it always disconnects me and prompts me to authenticate running systemctl. Any fix for this? I've tried looking for solutions but no luck

**Comment by ztefn** [comment]
Haguichi doesn't disconnect you. Hamachi crashes and then Haguichi notices the connection is gone and prompts you to start the service again. You can turn off auto-reconnect in preferences. Then you won't be prompted for authentication after Hamachi crashes.
