### ISSUE TITLE
AppCenter colors are low-contrast

### ISSUE THREAD

**Issue by cassidyjames** [ztefn/haguichi#46]
It looks like your AppCenter colors don't pass a contrast check:

![Screenshot from 2021-08-24 20-43-15@2x](https://user-images.githubusercontent.com/611168/130717902-0b6cab45-7cca-4e35-bf08-a8c693b70d90.png)

We recommend striving for AA contrast to ensure readability in AppCenter across device types and different folks' vision. You could darken the red and/or lighten the background to increase the contrast: 

![Screenshot from 2021-08-24 20-46-42@2x](https://user-images.githubusercontent.com/611168/130718063-6f4f9754-715a-4e01-8730-89986bd488c3.png)

**Comment by ztefn** [comment]
Yikes, these are my primary brand colors! I use them on the [website](https://haguichi.net/) as well. Actually quite fond of them myself...😅️

I shall try to find some more contrasty variation, at least for AppCenter.

**Comment by ztefn** [comment]
Now using these colors for AppCenter:
![Screenshot from 2021-08-25 14-19-01@2x](https://user-images.githubusercontent.com/343442/130791017-aab688c4-695d-42e8-8a1d-c1f95ab61cc8.png)
