### ISSUE TITLE
Consider using GLib.Notification or send desktop entry hint with Notify

### ISSUE THREAD

**Issue by danrabbit** [ztefn/haguichi#47]
Hey there! While reviewing your app for AppCenter, I noticed that your app is using LibNotify. This is a problem because your application doesn't currently identify itself to the notification server using the desktop-entry hint, which means that users can't use system-wide notification settings and notifications won't be properly grouped in the notification center.

I would suggest using GLib.Notification instead if you can. This will automatically set the desktop-entry hint, your app icon, etc and use the Notifications portal, so you won't need to manually specify the notifications dbus interface in your finish args.

If you do decide to go the GLib.Notification route we have some docs about using it here: https://docs.elementary.io/develop/apis/notifications

**Comment by ztefn** [comment]
Thanks for reporting! It seems that setting `desktop-entry` hint while using libnotify fixes the grouping, but the icon in the notification bubble is a generic info icon instead of app icon.

So I guess I will finally have to bite the bullet and port to `GLib.Notification`. 😅️

**Comment by ztefn** [comment]
@danrabbit I noticed when porting to `GLib.Notification` that on elementary OS 6 using `set_icon` will set a [badge icon](https://docs.elementary.io/develop/apis/notifications#badge-icons), even when the provided icon is the same as the application icon. This means that notifications for any application not build specifically for elementary OS that is setting its app icon will end up showing the same icon twice, one large and one small.
