### ISSUE TITLE
"Authentication is needed to run '/usr/bin/systemctl' as the super user"

### ISSUE THREAD

**Issue by andredebem** [ztefn/haguichi#49]
Hello!

I have installed Hamachi via .deb file without problems. After that, I installed Haguichi without problems too.

My problem is:

I can create and maintain an active network with other users, however, randomly, for no reason, hamachi apparently disconnects my connection and shows the following message on the screen:

"Authentication is needed to run "/usr/bin/systemctl" as the super user:

password:

Action: org.freeedesktop.policykit.exec"

After that my connection is disconnected and the networks obviously too. Everything just works again when I enter the password for this message.

My user is already the root of the system, and I didn't deny any permissions during installations.

Ubuntu 20.04 LTS

**Comment by andredebem** [comment]
![image](https://user-images.githubusercontent.com/78712956/135167327-fe28221d-d8d4-4e21-b9ed-f565b2215984.png)

**Comment by andredebem** [comment]
This bug is very annoying because I use hamachi to play with my friends and for no reason the hamachi dies and the network is disconnected. There is no pattern, it's completely random. Sometimes there's no one but me playing, and sometimes it happens when there are three people online.

**Comment by andredebem** [comment]
Apparently, the team responsible for Hamachi is not very interested in solving the problem: https://community.logmein.com/t5/LogMeIn-Hamachi-Discussions/Hamachi-randomly-disconnects-on-Ubuntu-20-04/td-p/222430

Damn it.

For over a year promising to solve the problem and so far nothing. Every Ubuntu 20.04 distro will have this same problem when using hamachi.

**Comment by ztefn** [comment]
So what exactly do you want me to do about it? I can't fix Hamachi...

**Comment by Descatres** [comment]
I've talked to the support of LogMeIn today via telephone and, afterwards, email with video and images of what happens. Let's hope it gets fixed :)
