### ISSUE TITLE
Haguichi Randomly quits

### ISSUE THREAD

**Issue by scorpium959** [ztefn/haguichi#50]
i use hamachi mostly for playing Garry's Mod with friends and some times i quit of the game at random moment and is because haguichi ask for my verification, how do i make that dont happen, pls halp.

![imagen](https://user-images.githubusercontent.com/64052400/147800572-c264fe22-af36-4408-be9e-d8625b9e8c86.png)

Post data i use the flatpak version, maybe this can help to fix this.

**Comment by ztefn** [comment]
Turn off the switch labeled "Reconnect automatically when the connection is lost" (_Reconectar cuando se pierda la conexión_) in the preferences window:
![Screenshot from 2022-01-04 13-14-16](https://user-images.githubusercontent.com/343442/148057838-6ff5c7b9-3965-4f5d-b9e6-bb3429c9f40c.png)

Now you won't be disturbed by Haguichi anymore asking you for authentication when this happens. You will need to reconnect manually when you want to restore the lost connection.
