### ISSUE TITLE
ZeroTier

### ISSUE THREAD

**Issue by iMonZ** [ztefn/haguichi#59]
Maybe adding support for ZeroTier would be nice.
Since it's been updated more regular then Hamachi

**Comment by ztefn** [comment]
Unfortunately the ZeroTier CLI (or its API's) is very different from Hamachi, therefore not really practical in the same GUI.

Also a Linux front-end for ZeroTier already exists, [ZeroTier-GUI](https://github.com/tralph3/ZeroTier-GUI). Have you tried that one?
