### ISSUE TITLE
Reconnecting again and again 

### ISSUE THREAD

**Issue by sundaram123krishnan** [ztefn/haguichi#60]
After login in onto my haguichi, it continuously gets disconnected.
Also facing lot of problems in ssh, not able ssh using virtual ip.
Using Ubuntu 22.04

**Comment by ztefn** [comment]
@sundaram123krishnan According to the resume on your website you are a software developer, right? Are you familiar with the concept of a front-end or GUI (graphical user interface) that gets it data from a back-end? Meet Haguichi, it talks to the Hamachi CLI (command line interface) to report the state and show your network list in a nice GTK interface. Haguichi doesn't gets disconnected, your Hamachi client get disconnected. Haguichi conveniently lets you know about it and even offers to (automatically) reconnect.

If you run the SSH command on a peer from within Haguichi, it will open the terminal application for you and passes along the command with virtual IP address. What happens after is not in any way controlled by Haguichi. It's up to your terminal, Hamachi client and SSH configuration.

So do you have any actual issue to report with Haguichi?

**Comment by sundaram123krishnan** [comment]
Yaa i am familiar with it, my all peers are using hamachi clients and i am the one using haguichi, the peers are able to ssh to my raspberry pi zero, but i was not able to ssh to their systems, so henceforth thought maybe haguichi is the reason.
Yaa, got it, it's not haguichi's fault.
