### ISSUE TITLE
Ubuntu 24.04 LTS (Noble Numbat) Support

### ISSUE THREAD

**Issue by InklingGirl** [ztefn/haguichi#61]
Hello, the latest LTS of Ubuntu is launching soon, may you please add support on `ppa:ztefn/haguichi-stable`? Thank you.

**Comment by ztefn** [comment]
Hello Christian,

Packages have now been published for Ubuntu 24.04 LTS in `ppa:ztefn/haguichi-stable`.

**Comment by InklingGirl** [comment]
Thank you for writing & maintaining great F/LOSS.
