### ISSUE TITLE
Убрать флаг Украины из русской локализации

### ISSUE THREAD

**Issue by zalimannard** [ztefn/haguichi#62]
Следующими коммитами был нанесён колосальный ущерб приложению:
- https://github.com/ztefn/haguichi/commit/215bd18dd8c1acb93decf9b2d314db6842fde62e
- https://github.com/ztefn/haguichi/commit/dc8c70f4567aaf83ef6c42953c7519dea838dba6

Внесённые правки не имеют никакого смысла кроме вредительства
- Линуксом пользуются всего несколько процентов пользователей компьютеров.
- Из всех пользователей линукса лишь небольшому проценту понадобится устанавливать это приложение.
- Из всех пользователей приложения лишь маленький процент окажется русскоговорящим - на нём говорят чуть больше 3% населения Земли.
- Даже если флаг Украины показывается для людей с русским языком, то на русском говорят не только в России. Большое количество русскоговорящих находится в самой Украине, также сюда относятся некоторые страны от бывшего СССР, как Казахстан или Беларусь, которые пользуются русским языком, но живут не в России и к ситуации не имеют никакого отношения.
- И даже если все вышеперечисленные пункты выполнены, то огромное количество пользователей окажется либо слишком молодым, либо неспособным что-либо сделать.
- Если пользователь в состоянии установить линукс и haguichi, то он явно не глупый и сможет сам понять что к чему и иконка другого цвета на его мнение никак не повлияет. Ссылка на Википедию с сайта haguichi тоже не поможет.

Могу с уверенностью сказать, что ПУТИН НЕ ПОЛЬЗУЕТСЯ HAGUICHI.

Зато рядовые пользователи должны почему-то видеть эту навязчивую рекламу куда не посмотри. Если делаешь свободное ПО, то будь добр - без политики. Иначе ты ничем не лучше любой несвободной организации.

Если ты правда хочешь помочь Украине, то могу предложить тебе:
- Идти воевать самому.
- Написать письмо Украинскому руководству с просьбой возобновить мирные переговоры с Россией.

Предлагаю:
- Либо заменить кнопку для русской локализации на указанную на скришоте
- Либо добавить стиль кнопки в украинской локализации
- Убрать флаг и быть вне политики

![Снимок экрана от 2024-08-03 14-45-22](https://github.com/user-attachments/assets/10651c82-4a07-4dc8-bedf-8bbcbdddf0ab)

Такого эффекта можно добиться используя следующий CSS-код:
background: linear-gradient(to bottom, #FFFFFF 33.333%, #0039A6 33.333%, #0039A6 66.667%, #D52B1E 66.667%);

**Comment by ztefn** [comment]
> Написать письмо Украинскому руководству с просьбой возобновить мирные переговоры с Россией.

I see no use of peace negotiations with Russia. They just need to GTFO of Ukraine.
