### ISSUE TITLE
Стать аполитичным приложением и убрать флаг Украины из русской локализации

### ISSUE THREAD

**Issue by zalimannard** [ztefn/haguichi#63]
Любой военный конфликт заканчивается мирными переговорами и то, что ты решил напакостить русским не приблизит этот момент. Вести мирные переговоры - единственный способ завершения конфликта. Форсирование украинской позиции только злит невиновных русских вынужденных мириться с приколами у вас в голове.

Приложения должны быть аполитичны.

На фронте никто не пользуется Haguichi. Им пользуются по большей части школьники и энтузиасты. Не Путин и военные. Не навязывай свою личную позицию всем в мире

**Comment by ztefn** [comment]
The Ukrainian flag will be removed from the russian localization once the last russian soldier is removed from Ukrainian soil and when russia has fully paid reparations for all the damages its caused. In the mean time, you have the option to not use this app if you are so bothered by it, or compile your own modified version so you won't be reminded of the war atrocities committed by your people.

While the russian schoolchildren you mention can happily live their undisturbed life in your apolitical utopia, Ukrainian children are being traumatized and killed by russian bombardments on kindergartens and maternity hospitals.
