### ISSUE TITLE
graphical glitch

### ISSUE THREAD

**Issue by AllHafRA** [ztefn/haguichi#64]
Hi. I found an error in the interface - the button for adding a network ("plus") glitched and turned into the colors of urine and blue. A very strange graphical glitch. It resembles the flag of collaborators in the Nazi-occupied territories of the USSR in the 40s of the last century.
![Снимок экрана_20240828_075345](https://github.com/user-attachments/assets/8aaf489c-1541-4dc0-bbe3-f34457eb743d)

**Comment by ztefn** [comment]
Your great leader Stalin was collaborator number one signing [a pact with the Nazis](https://en.wikipedia.org/wiki/Molotov%E2%80%93Ribbentrop_Pact). But I guess this chapter was skipped in your history class about the "Great Patriotic War".

**Comment by AllHafRA** [comment]
Is the Munich Agreement of 1938 also missing in your history? Have you
forgotten the US trade with Germany too? As well as all sorts of pacts of
England, France, the USA and Germany on plans against the USSR? By the way,
what can you say about the flag of a non-existent country in the interface
of a program that has nothing to do with politics?

ср, 28 авг. 2024 г. в 17:37, Stephen Brandt ***@***.***>:

**Comment by ztefn** [comment]
> By the way, what can you say about the flag of a non-existent country in the interface of a program that has nothing to do with politics?

I hate to break the news to you but the USSR dissolved in 1991 and Ukraine has been an [independent](https://en.wikipedia.org/wiki/Declaration_of_Independence_of_Ukraine) country ever since, even recognized by Russia on the first day after the referendum.
