### ISSUE TITLE
Hi ztefn !

### ISSUE THREAD

**Issue by cravlex** [ztefn/haguichi#67]
I would like to contact you, I am putting together a team for Hamachi. If you understand the structure of Hamachi, then I would like to talk with you about one topic and if you like it, then we will cooperate, if, of course, you want.

**Comment by ztefn** [comment]
You can contact me using the e-mail address described on the Haguichi website in the About → Contact section:
[https://haguichi.net/about/#contact](https://haguichi.net/about/?issue=67#contact)

**Comment by ztefn** [comment]
@cravlex Did you send me any e-mail? I don't seem to have received anything yet.
